-- ==========================================================
-- LHCA Courses Table (v2)
-- Fresh schema
-- ==========================================================


create table public.courses_new (
    id bigint generated by default as identity primary key,

    title text not null,
    description text,

    provider text,

    delivery_mode text
        check (
            delivery_mode in (
                'Online',
                'Face to Face',
                'Online or Face to Face',
                'Hybrid',
                'NA'
            )
        ),

    cost_gbp numeric(10,2)
        not null
        default 0
        check (cost_gbp >= 0),

    cost_category text,

    duration text,

    duration_category text,

    access text,

    education_outcome text,

    target_audience text[]
        not null
        default '{}',

    category text[]
        not null
        default '{}',

    sub_theme text[],

    url text,

    asset_category text,

    review_status text
        default 'Draft'
        check (
            review_status in (
                'Draft',
                'In Review',
                'Approved',
                'Archived',
                'NA'
            )
        ),

    image_url text,

    created_at timestamptz
        not null
        default now(),

    updated_at timestamptz
        not null
        default now()
);

------------------------------------------------------------
-- Indexes
------------------------------------------------------------

create index idx_courses_new_provider
    on public.courses_new(provider);

create index idx_courses_new_delivery_mode
    on public.courses_new(delivery_mode);

create index idx_courses_new_cost_gbp
    on public.courses_new(cost_gbp);

create index idx_courses_new_cost_category
    on public.courses_new(cost_category);

create index idx_courses_new_duration_category
    on public.courses_new(duration_category);

create index idx_courses_new_asset_category
    on public.courses_new(asset_category);

create index idx_courses_new_review_status
    on public.courses_new(review_status);

create index idx_courses_new_category
    on public.courses_new using gin(category);

create index idx_courses_new_sub_theme
    on public.courses_new using gin(sub_theme);

create index idx_courses_new_target_audience
    on public.courses_new using gin(target_audience);

------------------------------------------------------------
-- Auto-update updated_at
------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create trigger trg_courses_new_updated_at
before update on public.courses_new
for each row
execute function public.set_updated_at();

------------------------------------------------------------
-- Row Level Security
------------------------------------------------------------

alter table public.courses_new
enable row level security;

create policy Public read only
on public.courses_new
for select
using (true);

create policy Public no insert
on public.courses_new
for insert
with check (false);

create policy "Allow authenticated users to update courses"
on public.courses_new
for update
to authenticated
using (true)
with check (true);

create policy Public no delete
on public.courses_new
for delete
using (false);